// Package frontend provides the embedded React/Vite frontend assets.
// The dist/ directory contains the built SPA that can be served by the Go binary.
package frontend

import (
	"embed"
	"io/fs"
)

// distFS embeds the built frontend assets from the dist/ directory.
// These are generated by running `npm run build` in the frontend directory.
//
//go:embed dist/*
var distFS embed.FS

// DistFS returns the embedded filesystem containing frontend assets.
// The returned FS has paths prefixed with "dist/", so callers should
// use fs.Sub() to strip this prefix for serving.
func DistFS() fs.FS {
	return distFS
}
